apiVersion: v1
kind: Service
metadata:
  name: taxapp-svc
  labels:
    app: taxapp-app
spec:
  selector:
    app: taxapp-app
  ports:
    - name: taxapp
      protocol: TCP
      port: 3000
      targetPort: taxapp
